In [1]:
import pandas as pd
from Bio import SeqIO

df = pd.read_csv('/tscc/projects/ps-yeolab3/eboyle/encode/pipeline/adapters/katie/barcode_list.tsv', 
                   sep = '\t'
                  ).T.reset_index().T

In [2]:
df = df[[0,2]]

In [3]:
df.columns = ['name', 'seq']

In [4]:
df

           name                                          seq
index   eCseNA1  5Phos/NNAGCGCTAGAGATCGGAAGAGCACACGTC/3AmMO/
0       eCseNA2  5Phos/NNGATATCGAAGATCGGAAGAGCACACGTC/3AmMO/
1       eCseNA3  5Phos/NNCGCAGACGAGATCGGAAGAGCACACGTC/3AmMO/
2       eCseNA4  5Phos/NNTATGAGTAAGATCGGAAGAGCACACGTC/3AmMO/
3       eCseNA5  5Phos/NNCCTGAGATAGATCGGAAGAGCACACGTC/3AmMO/
4       eCseNA6  5Phos/NNTAGCGAGTAGATCGGAAGAGCACACGTC/3AmMO/
5       eCseNA7  5Phos/NNTTACTACGAGATCGGAAGAGCACACGTC/3AmMO/
6       eCseNA8  5Phos/NNAGGCTCCGAGATCGGAAGAGCACACGTC/3AmMO/
7       eCseNA9  5Phos/NNGCAGCGTAAGATCGGAAGAGCACACGTC/3AmMO/
8      eCseNA10  5Phos/NNCTGCGCATAGATCGGAAGAGCACACGTC/3AmMO/
9      eCseNA11  5Phos/NNGAGCGCTAAGATCGGAAGAGCACACGTC/3AmMO/
10     eCseNA12  5Phos/NNCGCTCAGTAGATCGGAAGAGCACACGTC/3AmMO/
11     eCseNA13  5Phos/NNGTCTTAGGAGATCGGAAGAGCACACGTC/3AmMO/
12     eCseNA14  5Phos/NNACTGATCGAGATCGGAAGAGCACACGTC/3AmMO/
13     eCseNA15  5Phos/NNTAGCTGCAAGATCGGAAGAGCACACGTC/3AmMO/
14     eCseNA16  5Phos/NNGACGTCGAAGATCGGAAGAGCACACGTC/3AmMO/
15     eCseNA17  5Phos/NNGTAAGGAGAGATCGGAAGAGCACACGTC/3AmMO/
16     eCseNA18  5Phos/NNTCGCCTTAAGATCGGAAGAGCACACGTC/3AmMO/
17     eCseNA19  5Phos/NNCTAGTACGAGATCGGAAGAGCACACGTC/3AmMO/
18     eCseNA20  5Phos/NNTTCTGCCTAGATCGGAAGAGCACACGTC/3AmMO/
19     eCseNA21  5Phos/NNGCTCAGGAAGATCGGAAGAGCACACGTC/3AmMO/

In [5]:
from Bio.Seq import Seq
df['barcode']=df['seq'].str.replace('AGATCGGAAGAGCACACGTC/3AmMO/', '').str.replace('5Phos/NN','').apply(lambda seq: str(Seq(seq).reverse_complement()))

In [6]:
df

           name                                          seq   barcode
index   eCseNA1  5Phos/NNAGCGCTAGAGATCGGAAGAGCACACGTC/3AmMO/  CTAGCGCT
0       eCseNA2  5Phos/NNGATATCGAAGATCGGAAGAGCACACGTC/3AmMO/  TCGATATC
1       eCseNA3  5Phos/NNCGCAGACGAGATCGGAAGAGCACACGTC/3AmMO/  CGTCTGCG
2       eCseNA4  5Phos/NNTATGAGTAAGATCGGAAGAGCACACGTC/3AmMO/  TACTCATA
3       eCseNA5  5Phos/NNCCTGAGATAGATCGGAAGAGCACACGTC/3AmMO/  ATCTCAGG
4       eCseNA6  5Phos/NNTAGCGAGTAGATCGGAAGAGCACACGTC/3AmMO/  ACTCGCTA
5       eCseNA7  5Phos/NNTTACTACGAGATCGGAAGAGCACACGTC/3AmMO/  CGTAGTAA
6       eCseNA8  5Phos/NNAGGCTCCGAGATCGGAAGAGCACACGTC/3AmMO/  CGGAGCCT
7       eCseNA9  5Phos/NNGCAGCGTAAGATCGGAAGAGCACACGTC/3AmMO/  TACGCTGC
8      eCseNA10  5Phos/NNCTGCGCATAGATCGGAAGAGCACACGTC/3AmMO/  ATGCGCAG
9      eCseNA11  5Phos/NNGAGCGCTAAGATCGGAAGAGCACACGTC/3AmMO/  TAGCGCTC
10     eCseNA12  5Phos/NNCGCTCAGTAGATCGGAAGAGCACACGTC/3AmMO/  ACTGAGCG
11     eCseNA13  5Phos/NNGTCTTAGGAGATCGGAAGAGCACACGTC/3AmMO/  CCTAAGAC
12     eCseNA14  5Phos/NNACTGATCGAGATCGGAAGAGCACACGTC/3AmMO/  CGATCAGT
13     eCseNA15  5Phos/NNTAGCTGCAAGATCGGAAGAGCACACGTC/3AmMO/  TGCAGCTA
14     eCseNA16  5Phos/NNGACGTCGAAGATCGGAAGAGCACACGTC/3AmMO/  TCGACGTC
15     eCseNA17  5Phos/NNGTAAGGAGAGATCGGAAGAGCACACGTC/3AmMO/  CTCCTTAC
16     eCseNA18  5Phos/NNTCGCCTTAAGATCGGAAGAGCACACGTC/3AmMO/  TAAGGCGA
17     eCseNA19  5Phos/NNCTAGTACGAGATCGGAAGAGCACACGTC/3AmMO/  CGTACTAG
18     eCseNA20  5Phos/NNTTCTGCCTAGATCGGAAGAGCACACGTC/3AmMO/  AGGCAGAA
19     eCseNA21  5Phos/NNGCTCAGGAAGATCGGAAGAGCACACGTC/3AmMO/  TCCTGAGC

# RBP to barcode

In [9]:
# MAP RBP TO BARCODE
import pandas as pd
exp_bar = pd.read_csv('../test_files/iter12_fix.csv')[['RBP', 'oligo']].dropna()

In [10]:
exp_bar['barcode'] = exp_bar['oligo'].map(df.set_index('name')['barcode'])
# exp_bar2['barcode'] = exp_bar2['oligo'].map(df.set_index('name')['barcode'])

In [11]:
exp_bar[['RBP', 'barcode']]

        RBP   barcode
0    RBFOX2  TCCTGAGC
1      PUM2  AGGCAGAA
2      DDX3  CGTACTAG
3   FAM120A  TAAGGCGA
4   ZC3H11A  CTCCTTAC
5    LIN28B  TCGACGTC
6     SF3B4  TGCAGCTA
7     EIF3G  CGATCAGT
8     PRPF8  CCTAAGAC
9   IGF2BP2  ACTGAGCG
10     SLBP  TAGCGCTC
11    CSTF2  ATGCGCAG
12     FXR2  TACGCTGC
13    G3BP2  CGGAGCCT
14      QKI  CGTAGTAA
15    TIAL1  ACTCGCTA
16      IgG  ATCTCAGG
17     Bead  TACTCATA
18  Spikein  CGTCTGCG

In [12]:
exp_bar['RBP'] = exp_bar['RBP'].str.replace(' ', '_')
# exp_bar2['RBP'] = exp_bar2['RBP'].str.replace(' ', '_')

In [16]:
exp_bar['barcode_w_name'] = exp_bar['barcode']+':'+exp_bar['RBP']
exp_bar['barcode_w_name'].to_csv('../config/barcode_csv/iter12.csv',index = False, header = False)

In [ ]:
# exp_bar2['barcode_w_name'] = exp_bar2['barcode']+':'+exp_bar2['RBP']
# exp_bar2['barcode_w_name'].to_csv('../config/barcode_csv/iter10-SLBP.csv',index = False, header = False)

In [17]:
exp_bar['barcode'].duplicated().any()

False

In [18]:
exp_bar

        RBP     oligo   barcode    barcode_w_name
0    RBFOX2  eCseNA21  TCCTGAGC   TCCTGAGC:RBFOX2
1      PUM2  eCseNA20  AGGCAGAA     AGGCAGAA:PUM2
2      DDX3  eCseNA19  CGTACTAG     CGTACTAG:DDX3
3   FAM120A  eCseNA18  TAAGGCGA  TAAGGCGA:FAM120A
4   ZC3H11A  eCseNA17  CTCCTTAC  CTCCTTAC:ZC3H11A
5    LIN28B  eCseNA16  TCGACGTC   TCGACGTC:LIN28B
6     SF3B4  eCseNA15  TGCAGCTA    TGCAGCTA:SF3B4
7     EIF3G  eCseNA14  CGATCAGT    CGATCAGT:EIF3G
8     PRPF8  eCseNA13  CCTAAGAC    CCTAAGAC:PRPF8
9   IGF2BP2  eCseNA12  ACTGAGCG  ACTGAGCG:IGF2BP2
10     SLBP  eCseNA11  TAGCGCTC     TAGCGCTC:SLBP
11    CSTF2  eCseNA10  ATGCGCAG    ATGCGCAG:CSTF2
12     FXR2   eCseNA9  TACGCTGC     TACGCTGC:FXR2
13    G3BP2   eCseNA8  CGGAGCCT    CGGAGCCT:G3BP2
14      QKI   eCseNA7  CGTAGTAA      CGTAGTAA:QKI
15    TIAL1   eCseNA6  ACTCGCTA    ACTCGCTA:TIAL1
16      IgG   eCseNA5  ATCTCAGG      ATCTCAGG:IgG
17     Bead   eCseNA4  TACTCATA     TACTCATA:Bead
18  Spikein   eCseNA3  CGTCTGCG  CGTCTGCG:Spikein

# good double checking practice

`zcat FASTQ_R2.fastq.gz | grep ONE_OF_THE_BARCODE`

for example,

`zcat /tscc/projects/ps-yeolab4/seqdata/20220920_KR_SM_clip/igm-storage2.ucsd.edu/220916_A00953_0627_BH5M7GDSX5/Lane3/CN1_S9_L003_R2_001.fastq.gz | grep ACTGAGCG`

yielded:

**ACTGAGCG**CCAGCAGCCTCCCCTCATCTGCATAGATCCGCGGCCAGGGTATTCCCCGCATAACAGTTCACATAGATCGGAAGAGCGTCGTGTAGGGAAAGA
ACTGAGCGGGATTGCCGGACGACGTCCTAAAGGAGGCCGGAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTCTTCGCCTGTGTAGATCTCGGTGGTCGC
ACTGAGCGATCCACCAACTAAGAACGGCCATGCACCACCACCCAAATGGGGCCGCAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTCTTCGCCTGTGTA
ACTGAGCGAATCCTGAGCTCAGGTGATCCACCCACCTCGGCAAATCGGTGGCAAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTCTAAGCCTGTGTAGA
ACTGAGCGCCCCTGGGAGACGGAGGTTGCAGTGAGCCGAGATGGCACCACTGCACAACTCTCAATCCAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTC
ACTGAGCGCCTGGCGGGGGTGCGTCGGGTCTGCACACTACGTGCAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTCTTCGCCTGTGTAGATCTCGGTGG
ACTGAGCGCAGAGCCTGCACCCCGCCTCCCGCGCGTCCCCACAAGATGAGCGGGAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTCTTCGCCTGTGTAG
ACTGAGCGGACCCCGATCCCCATCACGAACTACTGTGGGAGATCGGAAGAGCGTCGTGTAGGGACAGAGTGTCTTCGCCTGTGTAGATCTCGGTGGTCGCC
ACTGAGCGGTTGGGTCGTCGCCGCCACGGAAAGCGAGCGTGAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTCTTCGCCTGTGTAGATCTCGGTGGTC

the barcode should be in the beginning of read2

In [ ]:
zcat RBFOX2_Rep2_S2_R2_001.fastq.gz | sed -n '2~4p' | cut -c1-8 | sort | uniq -c > ~/scratch/barcode_count.tsv

In [ ]:
zcat Undetermined_S0_R2_001.fastq.gz | sed -n '2~4p' | cut -c1-8 | sort | uniq -c > ~/scratch/barcode_count_under.tsv

In [ ]:
import pandas as pd
cnt = pd.read_csv('/tscc/nfs/home/hsher/scratch/barcode_count_3gip_704.tsv', sep = r'\s+', names = ['count', 'seq'])
cnt = cnt[['count', 'seq']]

In [ ]:
cnt.sort_values(by = 'count')

In [ ]:
cnt.merge(df, left_on = 'seq', right_on = 'barcode')